Improve client b1 to implement 1
snek-at/client pull request #41
Opened 2020-05-25 11:22 UTC by schettn

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Documentation (non-breaking change which adds documentation)
 - [x] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently there is one method which handles all Apollo types. #37 
- Currently there are plenty of interfaces. #38 
- Currently it is not possible to perform a custom session aware task. #39 
- Currently the clients Apollo endpoint notation is misleading. #40 

**What is the new behavior (if this is a feature change)?**
- Now there are separate methods for each Apollo type. Closes #37 
- Now the number of interfaces has been removed by adding type parameter handling to Apollo endpoint. Closes #38 
- Now there it is possible to perform custom session aware tasks. Closes #39 
- Now the notation of the Apollo endpoint of clients has been adjusted. Currently the old version is still present but will be removed in a upcoming release. #40

**Other information**:
- Ref: 🐍

2020-05-25 11:29 UTC, pinterid commented on src/endpoints/apollo.ts
> +      );
Missing newline.

2020-05-25 11:31 UTC, pinterid commented on src/endpoints/index.ts
> +export type ApolloResult<T> =
Put export to the bottom of the file.

2020-05-25 11:33 UTC, pinterid commented on src/session/sessions.ts
> +   * @param {string} user A User defined by username and password.
Remove dot.

2020-05-25 11:33 UTC, pinterid commented on src/session/sessions.ts
> +   * @returns {Promise<any>} A UserData object.
Remove dot.

2020-05-25 11:37 UTC, pinterid commented on src/templates/snek/gql/tasks/auth.ts
>  /** @class A set of session aware Tasks */
Write "Tasks" in lower case.

2020-05-25 11:37 UTC, pinterid commented on src/templates/snek/gql/tasks/auth.ts
> +   * @returns {Promise<ApolloResult<AuthData>>} A JWT token.
Remove dot and is "token" needed in this case?

2020-05-25 11:38 UTC, pinterid commented on src/templates/snek/gql/tasks/auth.ts
> +   * @returns {Promise<ApolloResult<AuthData>>} A JWT token
Is "token" required here?

2020-05-25 11:38 UTC, pinterid commented on src/templates/snek/gql/tasks/auth.ts
> +   * @returns {Promise<ApolloResult<RefreshData>>} A JWT token
Is "token" required here?

2020-05-25 11:39 UTC, pinterid commented on src/templates/snek/gql/tasks/general.ts
> + *                             data
Missing dot.

2020-05-25 11:40 UTC, pinterid commented on src/templates/snek/gql/tasks/general.ts
> +   * @param {string} template A template set containing mutation and queries
Use the plural of "mutation"

2020-05-25 11:41 UTC, pinterid commented on src/templates/snek/gql/tasks/index.ts
> +    /* init tasks */
Change "init" to "Init"

2020-05-25 11:41 UTC, pinterid commented on src/templates/snek/gql/tasks/index.ts
> +      );
Missing newline.

2020-05-25 11:42 UTC, pinterid commented on src/templates/snek/gql/tasks/user.ts
> + *                        data.
Remove space before "data".

2020-05-25 11:43 UTC, pinterid commented on src/templates/snek/gql/tasks/user.ts
> +   * @param {string} template A template set containing mutation and queries
Use the plural of "mutation"

2020-05-25 11:43 UTC, pinterid commented on src/templates/snek/gql/tasks/user.ts
> +   * @returns {Promise<ApolloResult<RegistrationData>>} A JWT token
Is "token" required?

2020-05-25 11:43 UTC, pinterid commented on src/templates/snek/gql/tasks/user.ts
> +   * @returns {Promise<ApolloResult<CacheData>>} A JWT token
Is "token" required?

2020-05-25 11:43 UTC, pinterid requested changes
Looks good after some changes.

2020-05-25 11:50 UTC, schettn commented on src/templates/snek/gql/tasks/general.ts
> +   * @param {string} template A template set containing mutation and queries
Tis param should be removed totally.

2020-05-25 12:33 UTC, schettn commented on src/templates/snek/gql/tasks/user.ts
> +   * @param {string} template A template set containing mutation and queries
This should be removed.

2020-05-25 13:59 UTC, Aichnerc approved these changes
LGTM 🎁

2020-05-26 08:26 UTC, pinterid approved these changes
Looks good to merge.

2020-05-26 08:28 UTC, merged