Update client aa1 to implement 2
snek-at/client pull request #67
Opened 2020-11-07 18:25 UTC by schettn

**Checklist:**

 
 - [ ] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Documentation (non-breaking change which adds documentation)
 - [x] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently the client scraper lacks of most http methods
- Currently there is no instagram client
- Currently there minor errors in session awareness.
- Currently it is not possible to upload files.
- Currently there are tasks for snek calls.

**What is the new behavior (if this is a feature change)?**
- Now it there is a new method which allows performing all http methods.
- Now there is a instagram client
- Now the session refresh caused by an invalid token is fixed.
- Now it is possible to upload files.
- Now there are only tasks which are required for the session awareness. All other interaction
   should be handled by the session runner. `src/session/sessions.ts` 

**Other information**:
- 🐍

2020-11-09 20:22 UTC, pinterid requested changes
Some changes have to be done.

2020-11-09 20:22 UTC, pinterid commented on src/session/sessions.ts
> +
```suggestion
```

2020-11-09 20:22 UTC, pinterid commented on src/templates/instagram/tasks.ts
> +import * as paths from "./paths";
```suggestion
//#region > Imports
//> Sessions
// Contains the SNEK session
import { InstagramSession } from "../../session/sessions";
//> Instagram Endpoint paths
import * as paths from "./paths";
//#endregion
```

2020-11-09 20:22 UTC, pinterid commented on src/templates/snek/tasks/auth.ts
> +   * @returns {Promise<ApolloResult<GraphQLAuthentication>>} Authentication data.
```suggestion
   * @returns {Promise<ApolloResult<GraphQLAuthentication>>} Authentication data
```

2020-11-09 20:22 UTC, pinterid commented on src/templates/snek/tasks/index.ts
> +
```suggestion
//#endregion

//#region > Classes
```

2020-11-09 20:22 UTC, pinterid commented on src/templates/snek/tasks/index.ts
> +
```suggestion
//#endregion

```

2020-11-09 20:22 UTC, pinterid commented on src/templates/snek/types.ts
> +
Missing region for these exports?

2020-11-09 20:44 UTC, pinterid approved these changes
LGTM

2020-11-10 20:23 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-11-10 20:23 UTC, kleberbaum commented on src/endpoints/scraper.ts
> +
Please remove newline.
```suggestion
```

2020-11-10 20:23 UTC, kleberbaum commented on src/session/sessions.ts
> +
Please remove newline.
```suggestion
```

2020-11-10 20:23 UTC, kleberbaum commented on src/templates/snek/types.ts
> +//#region > Graphql Response Types for Authentication Related Requests
Extremely long region name.

2020-11-11 10:34 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-11-11 10:34 UTC, merged